services:
    mongodb:
        image: mongo:4.0.9
        container_name: mongodb
        hostname: mongodb
        volumes:
            - ./.docker/mongodb/mongod.conf:/etc/mongod.conf
            - ./.docker/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
            - ./.docker/mongodb/data/db/:/data/db/
            - ./.docker/mongodb/data/log/:/var/log/mongodb/
        env_file:
            - .env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        ports:
            - "27017:27017"
        command: ["-f", "/etc/mongod.conf"]
    backend_app:
        build: .
        container_name: backend_app
        hostname: backend_app
        environment:  
            MONGODB_URI: mongodb://${MONGO_INITDB_USERNAME}:${MONGO_INITDB_PASSWORD}@mongodb/${MONGO_INITDB_DATABASE}
            NODE_ENV: production
            SECRET: secret
        env_file:
            - .env
        depends_on:
            - mongodb
        ports: 
            - "3000:3000"


